const $=s=>document.querySelector(s);
const species=[{name:'Neon tetra',color:'#32c4d4',accent:'#ec584e',count:8,size:15,description:'A shimmering little school. Peaceful, social, and always on the move.'},{name:'Golden angelfish',color:'#d5b96c',accent:'#806e39',count:3,size:29,description:'Elegant fins and a curious nature. The graceful heart of your aquarium.'},{name:'Cherry barb',color:'#bd5b35',accent:'#e98f51',count:7,size:18,description:'Warm copper scales and an easygoing temperament. Happiest in a group.'},{name:'Pearl gourami',color:'#9daea1',accent:'#556b60',count:0,size:26,description:'Pearlescent scales and delicate feelers. A gentle explorer.'},{name:'Emerald rasbora',color:'#5eaa81',accent:'#e4b15e',count:0,size:15,description:'Tiny flashes of emerald among the leaves. An energetic schooling fish.'},{name:'Blue ram',color:'#6aa7cd',accent:'#dfad5e',count:0,size:23,description:'An iridescent blue resident with a wonderfully inquisitive personality.'}];
let state={night:false,temp:25,light:75,current:35,bubbles:true,habitat:'forest',counts:species.map(s=>s.count)};
try{const saved=JSON.parse(localStorage.getItem('stillwater-v1'));if(saved&&Array.isArray(saved.counts)&&saved.counts.length===6)state={...state,...saved,counts:saved.counts.map(n=>Math.max(0,Math.min(30,Math.floor(Number(n)||0))))}}catch{}
const canvas=$('#aquarium'),ctx=canvas.getContext('2d');let W=1100,H=490,dpr=1,fish=[],foods=[],clock=0,last=0,paused=false;
let seed=9371;const rand=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646};
const plants=Array.from({length:115},(_,i)=>({x:rand(),h:.12+rand()*.55,w:8+rand()*18,phase:rand()*7,hue:70+rand()*65,layer:i<45?0:1,type:rand()}));
const rocks=Array.from({length:26},()=>({x:.12+rand()*.78,y:.79+rand()*.13,r:.025+rand()*.085,seed:rand()*100}));
const particles=Array.from({length:100},()=>({x:rand(),y:rand(),r:.3+rand()*1.2,s:.15+rand()*.7}));
function resize(){const b=canvas.getBoundingClientRect();W=b.width;H=b.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}new ResizeObserver(resize).observe(canvas);
function save(){try{localStorage.setItem('stillwater-v1',JSON.stringify(state))}catch{toast('Your browser could not save this tank.')}}
function populate(){fish=[];state.counts.forEach((n,k)=>{for(let i=0;i<n;i++)fish.push({k,x:rand(),y:.18+rand()*.56,v:(rand()>.5?1:-1)*(.015+rand()*.02),phase:rand()*7,depth:.65+rand()*.5})})}populate();
function fishShape(c,k,x,y,size,dir=1,t=0){const s=species[k];c.save();c.translate(x,y);c.scale(dir,1);let wag=Math.sin(t)*.16;c.scale(1+wag*.15,1);let grad=c.createLinearGradient(0,-size*.5,0,size*.5);grad.addColorStop(0,s.color);grad.addColorStop(.48,k===0?'#b2dad0':s.color);grad.addColorStop(1,'#263d2c');c.fillStyle=grad;c.strokeStyle=s.accent;c.lineWidth=.6;
if(k===1){c.beginPath();c.moveTo(-size*.1,-size*.3);c.quadraticCurveTo(-size*.65,-size*1.4,-size*.25,-size*1.5);c.lineTo(size*.48,-size*.07);c.lineTo(-size*.3,size*1.4);c.quadraticCurveTo(-size*.45,size*.8,-size*.15,size*.2);c.fill();c.stroke();c.beginPath();c.ellipse(0,0,size*.6,size*.67,0,0,7);c.fill();c.stroke();c.strokeStyle='#3c412d88';c.lineWidth=size*.11;for(let q=-.3;q<.4;q+=.25){c.beginPath();c.moveTo(size*q,-size*.52);c.lineTo(size*q-size*.1,size*.52);c.stroke()}c.strokeStyle='#d9d4a391';c.lineWidth=.8;c.beginPath();c.moveTo(size*.25,size*.4);c.quadraticCurveTo(size*.1,size*1.2,-size*.2,size*1.65);c.stroke()}
else{c.beginPath();c.moveTo(-size*.7,0);c.lineTo(-size*1.15,-size*(.42+wag));c.quadraticCurveTo(-size*.94,0,-size*1.15,size*(.42-wag));c.closePath();c.fill();c.stroke();c.beginPath();c.moveTo(-size*.28,-size*.2);c.lineTo(-size*.15,-size*.65);c.lineTo(size*.35,-size*.2);c.fill();c.beginPath();c.ellipse(0,0,size*.82,size*.32,0,0,7);c.fill();c.stroke();if(k===0){c.fillStyle='#ed574a';c.beginPath();c.ellipse(-size*.22,size*.12,size*.42,size*.105,0,0,7);c.fill();c.shadowColor='#40d8f1';c.shadowBlur=5;c.strokeStyle='#67e3e9';c.lineWidth=size*.08;c.beginPath();c.moveTo(-size*.66,-size*.04);c.lineTo(size*.55,-size*.04);c.stroke();c.shadowBlur=0}c.fillStyle=s.accent+'66';c.beginPath();c.moveTo(0,size*.1);c.lineTo(-size*.2,size*.55);c.lineTo(size*.25,size*.2);c.fill()}
c.fillStyle='#e7dbab';c.beginPath();c.arc(size*.48,-size*.09,size*.1,0,7);c.fill();c.fillStyle='#13231e';c.beginPath();c.arc(size*.5,-size*.09,size*.055,0,7);c.fill();c.strokeStyle='#ffffff30';c.lineWidth=.6;c.beginPath();c.ellipse(size*.28,0,size*.13,size*(k===1?.38:.22),0,-1.4,1.4);c.stroke();c.restore()}
function icon(k){let c=document.createElement('canvas');c.width=180;c.height=80;fishShape(c.getContext('2d'),k,90,40,k===1?20:27,1,0);return `<svg viewBox="0 0 180 80" aria-hidden="true"><image href="${c.toDataURL()}" width="180" height="80"/></svg>`}
function updateUI(){const total=state.counts.reduce((a,b)=>a+b,0);$('#tank-count').textContent=total;$('#resident-badge').textContent=total;$('#tank-temp').textContent=state.temp;$('#metric-temp').textContent=state.temp;$('#time-label').textContent=state.night?'☾ Moonlight':'☀ Daylight';$('#cycle').innerHTML=state.night?'Night<small> / 12h</small>':'Day<small> / 12h</small>';$('#light-desc').textContent=state.night?'Rest & recharge':'Soft & natural';$('#day').classList.toggle('selected',!state.night);$('#night').classList.toggle('selected',state.night);$('#species-grid').innerHTML=species.slice(0,3).map((s,k)=>`<button class="species-card" data-species="${k}">${icon(k)}<strong>${s.name}</strong><small>${state.counts[k]} ${k===1?'gliding gracefully':'swimming happily'}</small></button>`).join('');document.querySelectorAll('[data-species]').forEach(b=>b.onclick=()=>catalog(false));}
function plant(p,t){const x=p.x*W,base=H*.94,h=p.h*H, sway=Math.sin(t*.6+p.phase)*h*.04,night=state.night;ctx.save();ctx.globalAlpha=p.layer===0?.48:.92;const hue=state.habitat==='river'?p.hue-16:p.hue;ctx.strokeStyle=`hsl(${hue},30%,${night?13:25}%)`;ctx.lineWidth=p.type>.6?2:1;ctx.beginPath();ctx.moveTo(x,base);ctx.quadraticCurveTo(x+sway*.4,base-h*.55,x+sway,base-h);ctx.stroke();if(p.type<.42){for(let i=0;i<6;i++){const yy=base-i*h*.14,xx=x+sway*i/6;for(let d of [-1,1]){const len=(.6+Math.sin(i*.5)*.5)*p.w*2;ctx.fillStyle=`hsl(${hue+i*2},${30+i*3}%,${(night?10:18)+i*2}%)`;ctx.beginPath();ctx.moveTo(xx,yy);ctx.bezierCurveTo(xx+d*len*.3,yy-h*.13,xx+d*len,yy-h*.13,xx+d*len,yy-h*.07);ctx.quadraticCurveTo(xx+d*len*.5,yy+3,xx,yy);ctx.fill();ctx.stroke()}}}else{for(let i=0;i<4;i++){const off=(i-1.5)*p.w*.6,tipx=x+off*2+sway;ctx.fillStyle=`hsl(${hue},${35+i*4}%,${(night?12:20)+i*3}%)`;ctx.beginPath();ctx.moveTo(x+off,base);ctx.bezierCurveTo(x+off*2+sway,base-h*.5,tipx-p.w*.4,base-h,tipx,base-h*(.75+i*.07));ctx.bezierCurveTo(tipx+p.w*.5,base-h*.6,x+off+p.w*.5,base-h*.2,x+off,base);ctx.fill();ctx.stroke()}}ctx.restore()}
function draw(t,dt){ctx.clearRect(0,0,W,H);let bg=ctx.createLinearGradient(0,0,W,H);bg.addColorStop(0,state.night?'#071d2b':'#24504a');bg.addColorStop(.4,state.night?'#081d2b':'#153d3c');bg.addColorStop(1,state.night?'#031018':'#071f25');ctx.fillStyle=bg;ctx.fillRect(0,0,W,H);
ctx.save();ctx.globalCompositeOperation='screen';for(let i=0;i<7;i++){const x=W*(.08+i*.13)+Math.sin(t*.1+i)*25;let beam=ctx.createLinearGradient(x,0,x+H*.3,H);beam.addColorStop(0,`rgba(${state.night?'88,153,213':'192,224,155'},${(state.night?.045:.10)*state.light/75})`);beam.addColorStop(1,'transparent');ctx.fillStyle=beam;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+W*.055,0);ctx.lineTo(x+H*.48,H);ctx.lineTo(x+H*.14,H);ctx.fill()}ctx.restore();
plants.filter(p=>p.layer===0).forEach(p=>plant(p,t));
// Sculptural branching driftwood, behind the living foreground.
ctx.save();ctx.lineCap='round';const wood=(x,y,ex,ey,width)=>{let g=ctx.createLinearGradient(x,y,x+width,y+width);g.addColorStop(0,'#514f35');g.addColorStop(.5,'#2e3527');g.addColorStop(1,'#172920');ctx.strokeStyle=g;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x,y);ctx.bezierCurveTo(x-W*.04,y-H*.2,ex+W*.08,ey+H*.12,ex,ey);ctx.stroke();ctx.strokeStyle='#79806525';ctx.lineWidth=width*.14;ctx.stroke()};wood(W*.50,H*.96,W*.39,H*.44,32);wood(W*.48,H*.86,W*.59,H*.31,20);wood(W*.52,H*.63,W*.7,H*.46,12);wood(W*.42,H*.59,W*.28,H*.41,13);wood(W*.55,H*.51,W*.53,H*.23,7);ctx.restore();
const sand=ctx.createLinearGradient(0,H*.86,0,H);sand.addColorStop(0,'#62694d');sand.addColorStop(.35,'#96947a');sand.addColorStop(1,'#414b3d');ctx.fillStyle=sand;ctx.beginPath();ctx.moveTo(0,H*.9);ctx.bezierCurveTo(W*.25,H*.82,W*.6,H*.97,W,H*.88);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();
seed=481;for(let i=0;i<2300;i++){const x=rand()*W,y=H*(.91+rand()*.09);ctx.fillStyle=rand()>.5?'#d3ccb137':'#172c2c60';ctx.fillRect(x,y,rand()*2+.3,rand()*1+.4)}
rocks.forEach(r=>{const x=r.x*W,y=r.y*H,rad=r.r*W;ctx.beginPath();for(let i=0;i<9;i++){let a=i/8*Math.PI*2,rr=rad*(.8+Math.sin(i*8+r.seed)*.16);const xx=x+Math.cos(a)*rr,yy=y+Math.sin(a)*rr*.55;i?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy)}ctx.closePath();const g=ctx.createLinearGradient(x-rad,y-rad*.5,x+rad,y+rad*.6);g.addColorStop(0,'#7a8070');g.addColorStop(.35,'#525e52');g.addColorStop(1,'#1c302b');ctx.fillStyle=g;ctx.fill();ctx.strokeStyle='#a8ad8230';ctx.lineWidth=1;ctx.stroke();ctx.save();ctx.clip();for(let i=0;i<15;i++){ctx.strokeStyle=i%2?'#263b3460':'#c0c1a01b';ctx.beginPath();ctx.moveTo(x-rad,y-rad+i*rad*.12);ctx.lineTo(x+rad,y-rad*.5+i*rad*.1);ctx.stroke()}ctx.restore()});
plants.filter(p=>p.layer===1).forEach(p=>plant(p,t));
fish.forEach(f=>{let target=foods.find(p=>!p.eaten);if(target){let dx=target.x-f.x,dy=target.y-f.y;f.v+=(Math.sign(dx)*.055-f.v)*Math.min(1,dt*2);f.y+=dy*dt*.48;if(Math.hypot(dx*W,dy*H)<18){target.eaten=true;}}else{f.y+=Math.sin(t*.8+f.phase)*dt*.007;if(f.x>.94)f.v=-Math.abs(f.v);if(f.x<.06)f.v=Math.abs(f.v)}f.x+=f.v*dt*(.5+state.current/70);f.x=Math.max(.02,Math.min(.98,f.x));f.y=Math.max(.08,Math.min(.83,f.y));ctx.globalAlpha=state.night?.57:.8+f.depth*.12;fishShape(ctx,f.k,f.x*W,f.y*H,species[f.k].size*f.depth*Math.min(W/1000,1.2),f.v>=0?1:-1,t*5+f.phase);ctx.globalAlpha=1});
foods.forEach(p=>{p.y+=dt*.025;p.x+=Math.sin(t+p.y*8)*dt*.002;ctx.fillStyle='#c69555';ctx.beginPath();ctx.arc(p.x*W,p.y*H,2,0,7);ctx.fill()});foods=foods.filter(p=>!p.eaten&&p.y<.92);
particles.forEach(p=>{let y=(p.y-t*.003*p.s+10)%1;ctx.fillStyle='#e2f5c526';ctx.beginPath();ctx.arc(p.x*W+Math.sin(t*.4+p.y*10)*4,y*H,p.r,0,7);ctx.fill()});if(state.bubbles)for(let i=0;i<18;i++){let y=1-((t*.045+i*.071)%1),x=W*.91+Math.sin(t+i*2)*7+Math.sin(i)*12;ctx.strokeStyle='#cceadd32';ctx.lineWidth=.65;ctx.beginPath();ctx.arc(x,y*H,1.3+i%4*.7,0,7);ctx.stroke();ctx.fillStyle='#e7fff047';ctx.fillRect(x-1,y*H-1,1,1)}
let vignette=ctx.createRadialGradient(W*.48,H*.4,H*.15,W*.5,H*.5,W*.65);vignette.addColorStop(0,'transparent');vignette.addColorStop(1,'#021415aa');ctx.fillStyle=vignette;ctx.fillRect(0,0,W,H);if(state.night){ctx.fillStyle='#07112f55';ctx.fillRect(0,0,W,H)}
}
function loop(now){let dt=Math.min((now-last)/1000||0,.04);last=now;if(!document.hidden){clock+=dt;draw(clock,dt)}requestAnimationFrame(loop)}requestAnimationFrame(loop);
let toastTimer;function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200)}
function feed(x=.3+Math.random()*.4,y=.12){if(foods.length>55){toast('There’s plenty of food already. Let them enjoy it.');return}for(let i=0;i<12;i++)foods.push({x:x+(Math.random()-.5)*.05,y:y+Math.random()*.03});toast('Dinner is served. Watch them gather.')}canvas.onclick=e=>{const b=canvas.getBoundingClientRect();feed((e.clientX-b.left)/b.width,(e.clientY-b.top)/b.height)};$('#feed').onclick=()=>feed();
function modal(title,html){$('#modal-title').textContent=title;$('#modal-content').innerHTML=html;$('#panel').showModal()}$('#close').onclick=()=>$('#panel').close();$('#panel').onclick=e=>{if(e.target===$('#panel')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}};
function catalog(add=true){modal(add?'Add a little life':'Meet your residents',`<p class="help-copy">A little diversity brings your world to life. Your tank has room for 60 residents.</p>${species.map((s,k)=>`<div class="catalog-row">${icon(k)}<div><h3>${s.name} <small style="color:#8a987f">· ${state.counts[k]}</small></h3><p>${s.description}</p></div><button class="secondary" data-add="${k}">＋ Add</button>${state.counts[k]?`<button class="icon-btn" data-remove="${k}" aria-label="Remove one ${s.name}">−</button>`:''}</div>`).join('')}`);document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const k=+b.dataset.add;if(fish.length>=60){toast('Your aquarium is full — 60 residents.');return}state.counts[k]++;fish.push({k,x:.15+Math.random()*.7,y:.2+Math.random()*.4,v:.025,phase:Math.random()*7,depth:.9});save();updateUI();$('#panel').close();catalog(add);toast(`A ${species[k].name.toLowerCase()} has moved in.`)});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const k=+b.dataset.remove;state.counts[k]--;fish.splice(fish.findIndex(f=>f.k===k),1);save();updateUI();$('#panel').close();catalog(add)})}
$('#add').onclick=()=>catalog();$('#all-species').onclick=()=>catalog(false);
function lighting(n){state.night=n;save();updateUI();toast(n?'Moonlight on. Time to slow down.':'A new day in your little world.')}$('#day').onclick=()=>lighting(false);$('#night').onclick=()=>lighting(true);
function settings(){modal('Find your balance',`<div class="setting"><label for="temp">Water temperature <b id="temp-value">${state.temp} °C</b></label><input id="temp" type="range" min="22" max="28" value="${state.temp}"></div><div class="setting"><label for="light">Light intensity <b id="light-value">${state.light}%</b></label><input id="light" type="range" min="20" max="100" value="${state.light}"></div><div class="setting"><label for="current">Water current <b id="current-value">${state.current}%</b></label><input id="current" type="range" min="0" max="100" value="${state.current}"></div><div class="setting"><label for="habitat">Plant palette</label><select id="habitat"><option value="forest">Emerald forest</option><option value="river">Golden riverbank</option></select></div><div class="setting"><label for="bubbles">Bubble stream <input id="bubbles" type="checkbox" ${state.bubbles?'checked':''}></label><p>Water readings are simulated for this digital habitat.</p></div>`);['temp','light','current'].forEach(key=>$('#'+key).oninput=e=>{state[key]=+e.target.value;$('#'+key+'-value').textContent=state[key]+(key==='temp'?' °C':'%');save();updateUI()});$('#habitat').value=state.habitat;$('#habitat').onchange=e=>{state.habitat=e.target.value;save()};$('#bubbles').onchange=e=>{state.bubbles=e.target.checked;save()}}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{if(b.dataset.view==='species')catalog(false);else if(b.dataset.view==='settings')settings();else{document.body.classList.remove('zen');$('#panel').close()}});
$('#snapshot').onclick=()=>{const link=document.createElement('a');link.download='stillwater-'+new Date().toISOString().slice(0,10)+'.png';link.href=canvas.toDataURL('image/png');link.click();toast('A little moment, captured. Snapshot downloaded.')};
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#tank-wrap').requestFullscreen()}catch{document.body.classList.add('zen')}};$('#zen').onclick=()=>document.body.classList.add('zen');$('#exit-zen').onclick=()=>document.body.classList.remove('zen');
let audioCtx,audioSource,audioGain,soundOn=false;$('#sound').onclick=async()=>{try{if(!audioCtx){audioCtx=new AudioContext();const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*4,audioCtx.sampleRate);const data=buffer.getChannelData(0);let brown=0;for(let i=0;i<data.length;i++){brown=(brown+Math.random()*.04-.02)/1.02;data[i]=brown*3}audioSource=audioCtx.createBufferSource();audioSource.buffer=buffer;audioSource.loop=true;const filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=550;audioGain=audioCtx.createGain();audioGain.gain.value=0;audioSource.connect(filter);filter.connect(audioGain);audioGain.connect(audioCtx.destination);audioSource.start()}await audioCtx.resume();soundOn=!soundOn;audioGain.gain.setTargetAtTime(soundOn?.38:0,audioCtx.currentTime,.4);$('#sound').innerHTML=`<span>♫</span> Sound ${soundOn?'on':'off'}`;$('#sound').setAttribute('aria-pressed',soundOn)}catch{toast('Ambient audio is unavailable in this browser.')}};
$('#help').onclick=()=>modal('Welcome to your sanctuary',`<p class="help-copy">This is your own living digital aquarium. Click the water to drop food and watch the fish gather. Add species, adjust the current, or let the moonlight take over.</p><div class="setting help-copy"><b>F</b> — Feed your fish<br><b>N</b> — Switch day and night<br><b>Z</b> — Enter or leave zen mode<br><b>Escape</b> — Leave zen mode or close a panel</div><p class="help-copy">Your residents and tank settings save automatically on this browser. Snapshots download as PNG images. Ambient water sound is generated on your device.</p>`);
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.body.classList.remove('zen');if(e.target.matches('input,select,textarea')||$('#panel').open)return;if(e.key.toLowerCase()==='f')feed();if(e.key.toLowerCase()==='n')lighting(!state.night);if(e.key.toLowerCase()==='z')document.body.classList.toggle('zen')});updateUI();

$("#mobile-settings").onclick=settings;
